baseurl: http://luminousbe.es
encoding: utf-8
permalink: ./:year/:month/:title/

exclude:
  - README.md

gems:
  - jekyll-sitemap
  - jekyll-gist

markdown: kramdown

lib:
  semantic:
    baseurl: https://cdnjs.cloudflare.com/ajax/libs/semantic-ui
    version: 2.1.8
  jquery:
    baseurl: https://code.jquery.com
    version: 3.0.0
